routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {return view('welcome'); });
Route::get('/home', 'HomeController@index')->name('home');

Route::get('berita/table', 'beritaCtrl@table')->name('berita.table');
Route::get('berita/populer', 'beritaCtrl@populer')->name('berita.populer');
Route::resource('berita', 'beritaCtrl');

Route::resource('peraturan', 'peraturanCtrl');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/beritaCtrl.php
<?php

namespace App\Http\Controllers;

use App\Model\Berita;
use Illuminate\Http\Request;

class beritaCtrl extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $berita = Berita::orderBy('id', 'desc')->paginate(5);

        return view ('berita.index')->with('berita', $berita);
    }

    public function table()
    {
        $berita = Berita::orderBy('created_at', 'desc')->paginate(20);

        return view ('berita.table')->with('berita', $berita);
    }

    public function populer() 
    {
        $populer = Berita::orderBy('hits', 'desc')->paginate(5);
        
        return view ('berita.populer')->with('populer', $populer);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $berita = Berita::all();
        return view ('berita.create')->with('berita', $berita);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Berita::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $berita = Berita::find($id);

        return view('berita.show')->with('berita', $berita);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita = Berita::find($id);
        
        return view('berita.show')->with('berita', $berita);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Berita $berita)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function destroy(Berita $berita)
    {
        //
    }
}

app/Http/Controllers/peraturanCtrl.php
<?php

namespace App\Http\Controllers;

use App\Model\Peraturan;
use Illuminate\Http\Request;

class peraturanCtrl extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Peraturan  $peraturan
     * @return \Illuminate\Http\Response
     */
    public function show(Peraturan $peraturan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Peraturan  $peraturan
     * @return \Illuminate\Http\Response
     */
    public function edit(Peraturan $peraturan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Peraturan  $peraturan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Peraturan $peraturan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Peraturan  $peraturan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Peraturan $peraturan)
    {
        //
    }
}

app/Http/Controllers/tagCtrl.php
<?php

namespace App\Http\Controllers;

use App\Model\Tag;
use Illuminate\Http\Request;

class tagCtrl extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        //
    }
}

resources/views/_c/_banner.blade.php
<div class="row">
    
</div>

resources/views/_c/_berita.blade.php
<div class="row">
    <div class="col-md-12">
        <h4 class="text-center">Berita Desa</h4>
        <h6 class="text-center">Dibuat dengan
            <i class="fa fa-fw fa-heart text-danger"></i> Oleh <a href="#" class="btn btn-primary btn-xs" target="_blank">Desa Karema</a>
        </h6>
    </div>
</div>
<hr>
@foreach ($berita as $brt)
<div class="row">
<div class="col-md-4">
    <div class="berita-image">
    <img src="img/berita/{{$brt->gambar }}" class="img-thumbnail" alt="Image" width="100%">
    </div>
</div>
<div class="col-md-8">

    <div id="berita">
        <div class="berita-title">
        <h4>{{$brt->judul}}</h4>
        </div>
        <div class="berita-info">
        <span class="label label-default">Uploader: NS</span>
        <span class="label label-default">{{ Carbon\Carbon::parse($brt->created_at)->diffForHumans() }}</span>
        <!--
        <span class="label label-default">{{ date('d F Y  - H:i',strtotime($brt->created_at)) }}</span>
        -->
        <span class="label label-default">Category: Berita</span>
     
        </div>
        <hr>
        <div class="berita-body">
        <p>
        {{ substr($brt->berita,0,200) }} {{ strlen($brt->berita) > 50 ? "..." : "" }}
           <a href="{{route('berita.show', $brt->id)}}"><button class="btn btn-xs btn-success">Selengkapnya <i class="fa fa-fw fa-eye"></i></button></a>
        </p>
        </div>
    
        <div class="berita-footer">
        <div class="text-right">
         
            @if ( Auth::check() )
            <a href="#"><button class="btn btn-sm btn-primary"><i class="fa fa-fw fa-edit"></i> Edit</button></a>
            @endif
        </div>
        </div>
        <hr>
    </div>
     
</div>
</div>
@endforeach

resources/views/_c/_breadcrumb.blade.php
<ul class="page-breadcrumb list-inline">
    <li>
        <a href="/" class="btn btn-primary btn-sm"><i class="fa fa-home fa-lg"></i></a>
        
    </li>
    @for($i = 1; $i <= count(Request::segments()); $i++)
    <li> 
        
        <a href="" class="btn btn-success btn-xs">{{Request::segment($i)}}</a>
        @if($i < count(Request::segments()) & $i > 0)
        {!!'<i class="fa fa-angle-double-right fa-lg"></i>'!!}
        @endif
    </li>
    @endfor
    
</ul>

resources/views/_c/_login.blade.php
<div class="text-center">
        <a href="{{route('login')}}">
          <button class="btn btn-success btn-sm ">
           <i class=" fa fa-sign-in fa-fw"></i>&nbsp;Masuk
          </button>
        </a>

        <a href="{{route('register')}}">
          <button class="btn btn-default btn-sm  ">
            Daftar&nbsp;<i class="fa fa-registered fa-fw"></i>
          </button>
        </a>
        <div style="margin:5px; border-bottom:2px solid #abc"> </div>
        <button class="btn btn-primary btn-sm btn-block ">
            Forum &nbsp;<i class="fa fa-comments fa-fw"></i>
        </button>
</div>

resources/views/_c/_sidemenu.blade.php
<div>
    <a href="{{route('berita.index')}}">
        <button type="button" class="btn btn-success btn-block btn-sm">
            <span class="pull-left"><h5>Berita Desa</h5></span>&nbsp;
            <span class="pull-right"><h5><i class="fa fa-newspaper-o fa-lg"></i></h5></span>&nbsp;
        </button>
    </a>


    <a href="{{route('peraturan.index')}}">
        <button type="button" class="btn btn-primary btn-block btn-sm">
            <span class="pull-left"><h5>Agenda Desa </h5></span>&nbsp;
            <span class="pull-right"><h5><i class="fa fa-calendar-times-o fa-lg"></i></h5></span>&nbsp;
        </button>
    </a>


    <a href="{{route('peraturan.index')}}">
        <button type="button" class="btn btn-danger btn-block btn-sm">
            <span class="pull-left"><h5>Peraturan Desa</h5></span>&nbsp;
            <span class="pull-right"><h5><i class="fa fa-institution fa-lg"></i></h5></span>&nbsp;
        </button>
    </a>

</div>

resources/views/_c/_slider.blade.php
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" id="whole">
        <div id="logo-desa">
            <img src="img/mamuju.png" alt="" height="100px"><br>
            <h3> 
              <span class="label label-success">Desa Karema</span> 
            </h3>
            
            <h4><span class="label label-default">Jl. Abdul Malik Pattana Endeng - Mamuju</span></h4> 
        </div>
        <div class="item active">
        <img src="img/mamuju-malam.jpg" alt="Chania" style="width:100%;height:300px">
            <div class="carousel-caption">
                
            </div>
        </div>

        <div class="item">
        <img src="img/rumah-adat.jpg" alt="Chania" style="width:100%;height:300px">
            <div class="carousel-caption">
            
            </div>
        </div>

        <div class="item">
        <img src="img/mamuju-laut.jpg" alt="Chania" style="width:100%;height:300px">
            <div class="carousel-caption">
                
            </div>
        </div>
    </div>
</div>

resources/views/_l/_breadcrumb.blade.php
<div class="row">
  <div class="col-md-9">
      <ul class="page-breadcrumb list-inline">
        <li>
          <a href="/" class="btn btn-primary btn-sm"><i class="fa fa-home fa-lg"></i></a>
         
        </li>
        @for($i = 1; $i <= count(Request::segments()); $i++)
        <li> 
          
          <a href="" class="btn btn-success btn-xs">{{Request::segment($i)}}</a>
          @if($i < count(Request::segments()) & $i > 0)
            {!!'<i class="fa fa-angle-double-right fa-lg"></i>'!!}
          @endif
        </li>
        @endfor
      </ul>
  <hr style="border: 1px solid #ccc">
  </div>
  <div class="col-md-3">
    <div class="panel panel-info text-center">
      <div class="panel-body">
        <button class="btn btn-default btn-sm">
          Login
        </button>
        <button class="btn btn-primary btn-sm">
          Forum
        </button>
      </div>
    </div>
  </div>
</div>

resources/views/_l/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="token" id="token" value="{{ csrf_token() }}">
<title>SID - @yield('title')</title>


<!-- Loader -->
<!-- <link href="/css/loader.css" rel="stylesheet"> -->
<!-- Main CSS Bootstrap & FontAwesome as app.css -->
<link href="{{asset('css/app.css')}}" rel="stylesheet">
<link href="{{asset('css/sid.css')}}" rel="stylesheet">

<!-- Extra Java Script or CSS -->
@yield('extra')

resources/views/_l/_navbot.blade.php
    <div class="row">
      <div class="col-md-12">
          <div class="nav navbar-default">
              <!-- Left Side Of Navbar -->
             
                <!-- Branding Image -->
                 
                <div class="navbar-header">
                    <ul class="nav navbar-nav ">
                        <li>&nbsp; &nbsp; © Copyright 2017 - Desa Karema</li> 
                    </ul>
                </div>
                <div class="navbar-header pull-right">
                  <!-- Right Side Of Navbar -->
                  <ul class="nav navbar-nav collapse navbar-collapse pull-right">
                    <!-- Authentication Links -->
                      <li><a href="#">Disclaimer</a></li>
                      <li><a href="#">Syarat & Ketentuan</a></li>
                      <li><a href="#">FAQ</a></li>
                  </ul>
                  <!-- Collapsed Hamburger -->
              </div>
        
          </div>
      </div>
    </div>

  

resources/views/_l/_scripts.blade.php
<!-- Main Scripts -->
<!-- jQuery & Bootstrap as app.js (necessary for Bootstrap's JavaScript plugins) -->
<script src="{{asset('js/app.js')}}"></script>

<script>
  // For Ajax Form
  window.Laravel =  <?php echo json_encode([ 'csrfToken' => csrf_token() ]); ?>
</script>


@yield ('bot-scripts')

resources/views/_l/_session.blade.php
<div class="container">
  @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
      <strong>Success:</strong> {{Session::get('success')}}
    </div>
  @endif

  @if(count($errors) > 0 )
    <div class="alert alert-warning" role="alert">
      <strong>Error:</strong>
      <ul>
        @foreach($errors->all() as $error)
          <li>
            {{ $error }}
          </li>
        @endforeach
      </ul>
    </div>

  @endif
</div>

resources/views/_l/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/_l/main.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>
    @include('_l._head')
  
  </head>
  <body>    
    <!--  Main Contents -->
    <div class="container">
      @include('_l._navtop')
      <div id="app">

         @yield('content')
      </div>
      @include('_l._navbot')
    </div>


    <!--  Navigation Bottom-->


    <!-- The Scripts -->
    @include('_l._scripts')
  </body>

  <footer>
    <!-- The Foot -->
    @include('_l._foot')
  </footer>
</html>

resources/views/berita/create.blade.php
@extends('_l.main')

@section('title')
   Buat Berita
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
        @include('_c._breadcrumb')
            <div class="panel panel-default" style="min-height:450px">
                <div class="panel-body">
                    <h4 class="text-center"><b>Tambah Berita</b></h4>
                    <hr>
                     <form class="form-horizontal" method="POST" action="{{ route('berita.store') }}">
                        {{ csrf_field() }}
                        <div class="col-md-4 col-md-offset-2 ">
                            <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                <label for="judul" class="control-label">Judul:</label>
                                <input id="judul" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-3 col-md-offset-1">
                            <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                <label for="gambar" class="control-label">Gambar:</label>
                                <input id="gambar" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                   
                      

                        
                        <div class="col-md-8 col-md-offset-2 ">
                            <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                <label for="berita" class="control-label">Berita:</label>
                                <textarea id="berita" type="text" rows="5" class="form-control" name="berita" value="{{ old('berita') }}" required autofocus>
                                </textarea>
                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-4 col-md-offset-2 ">
                            <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                <label for="judul" class="control-label">Tags:</label>
                                <input id="judul" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-3 col-md-offset-1">
                            <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                                <label for="updated_at" class="control-label">Tanggal Posting:</label>
                                <input id="updated_at" type="datetime-local" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-8 col-md-offset-2">
                             <div class="form-group">
                           
                                <button type="submit" class="btn btn-primary btn-sm  btn-block">
                                    Tambah Berita
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            
            </div>
        </div>
    </div>
@endsection

resources/views/berita/edit.blade.php
@extends('_l.main')

@section('title')
   {{$berita->judul}}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default" style="min-height:450px">
                <div class="panel-body">
                    <h4>{{$berita->judul}}</h4>
                    <p>{{$berita->berita}}</p>
                </div>
            </div>
            
        </div>
    </div>
@endsection

resources/views/berita/index.blade.php
@extends('_l.main')

@section('title')
    Berita Desa
@endsection

@section('content')
    
    <div class="row">
        <div class="col-md-8">
            @include('_c._breadcrumb')
            <div class="panel panel-default">
                <div class="panel-body">
                    @include('_c._berita')
                  
                </div>
            </div>
        </div>
        <div class="col-md-4">
            @include('berita.nav')
            
            @include('berita.populer')
        </div>
    </div>
     
@endsection

resources/views/berita/populer.blade.php
<div class="panel panel-default">
    <div class="panel-body">
       <h4>
            <span class="label label-primary">
                Berita Terpopuler
            </span>
       </h4>
        <hr>
        <ol class="list-unstyled">
        @foreach($populer as $p)
            <li><a href="{{route('berita.show', $p->id)}}">{{$p->judul}} </a><span class="pull-right">{{$p->hits}} <i class="fa fa-eye-slash"></i></span></li>
        @endforeach
        </ol>
    </div>
</div>